webserver:
  listen: "0.0.0.0:3000"
  enable_tls: false
  tls_cert: "/path/to/cert.pem"
  tls_key: "/path/to/key.pem"
  auth_provider: basic # options: basic, azuread
  users: # used only if auth_provider is basic
    "admin": "admin"
    "user": "user"
  azuread_key: "AZUREAD_KEY" # used only if auth_provider is azuread
  azuread_secret: "AZUREAD_SECRET" # used only if auth_provider is azuread
  azuread_callback: "http://localhost:3000/auth/azuread/callback" # used only if auth_provider is azuread
  timeout_default: 30
  timeout_max: 3000

services:
  Chromium:
    provider: "docker" # only option for now
    docker_image: "docker.io/accetto/ubuntu-vnc-xfce-chromium-g3:latest"
    docker_port: "6901"
  Firefox:
    provider: "docker" # only option for now
    docker_image: "docker.io/accetto/ubuntu-vnc-xfce-firefox-g3:latest"
    docker_port: "6901"
