on:
  release:
    types: [created]
name: Build Release
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        projects: ["allhash","elasticdump","fakedns","identme","pebble-cli","proxyenv","sctptunnel","siemsend","sniplex","sockstls","spitcurl","sshproxy"]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@master
      env:
        CGO_ENABLED: 0 # support alpine
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: ${{ matrix.projects }}
        asset_name: ${{ matrix.projects }}-${{ matrix.goos }}-${{ matrix.goarch}}
        binary_name: ${{ matrix.projects }}
